name: Node.js CI/CD with EC2

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ${{ secrets.AWS_EC2_USER }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        port: 22
        script: |
          # Navigate to the application directory
          cd ~/ifixit-inventory # Update this path to match your EC2 directory

          # Pull the latest changes from the repository
          git pull origin main

          # Install updated dependencies
          npm install


          # Restart the application using PM2
          pm2 restart inventory
